In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt



In [5]:
df=pd.read_csv('adult.csv')

In [6]:
df.head()

39          State-gov   77516   Bachelors   13        Never-married  \
0  50   Self-emp-not-inc   83311   Bachelors   13   Married-civ-spouse   
1  38            Private  215646     HS-grad    9             Divorced   
2  53            Private  234721        11th    7   Married-civ-spouse   
3  28            Private  338409   Bachelors   13   Married-civ-spouse   
4  37            Private  284582     Masters   14   Married-civ-spouse   

         Adm-clerical   Not-in-family   White     Male   2174   0   40  \
0     Exec-managerial         Husband   White     Male      0   0   13   
1   Handlers-cleaners   Not-in-family   White     Male      0   0   40   
2   Handlers-cleaners         Husband   Black     Male      0   0   40   
3      Prof-specialty            Wife   Black   Female      0   0   40   
4     Exec-managerial            Wife   White   Female      0   0   40   

    United-States   <=50K  
0   United-States   <=50K  
1   United-States   <=50K  
2   United-States   <=50K  
3            Cuba   <=50K  
4   United-States   <=50K

In [7]:
df.columns


Index(['39', ' State-gov', ' 77516', ' Bachelors', ' 13', ' Never-married',
       ' Adm-clerical', ' Not-in-family', ' White', ' Male', ' 2174', ' 0',
       ' 40', ' United-States', ' <=50K'],
      dtype='object')

In [8]:
df.columns=['Age', 'Workclass','Fnlwgt','Education','education_num','marital_status','occupation','relationship','race','sex','capital_gain','capital_loss','hours_per_week','native_country','income']
df

Age          Workclass  Fnlwgt    Education  education_num  \
0       50   Self-emp-not-inc   83311    Bachelors             13   
1       38            Private  215646      HS-grad              9   
2       53            Private  234721         11th              7   
3       28            Private  338409    Bachelors             13   
4       37            Private  284582      Masters             14   
...    ...                ...     ...          ...            ...   
32555   27            Private  257302   Assoc-acdm             12   
32556   40            Private  154374      HS-grad              9   
32557   58            Private  151910      HS-grad              9   
32558   22            Private  201490      HS-grad              9   
32559   52       Self-emp-inc  287927      HS-grad              9   

            marital_status          occupation    relationship    race  \
0       Married-civ-spouse     Exec-managerial         Husband   White   
1                 Divorced   Handlers-cleaners   Not-in-family   White   
2       Married-civ-spouse   Handlers-cleaners         Husband   Black   
3       Married-civ-spouse      Prof-specialty            Wife   Black   
4       Married-civ-spouse     Exec-managerial            Wife   White   
...                    ...                 ...             ...     ...   
32555   Married-civ-spouse        Tech-support            Wife   White   
32556   Married-civ-spouse   Machine-op-inspct         Husband   White   
32557              Widowed        Adm-clerical       Unmarried   White   
32558        Never-married        Adm-clerical       Own-child   White   
32559   Married-civ-spouse     Exec-managerial            Wife   White   

           sex  capital_gain  capital_loss  hours_per_week  native_country  \
0         Male             0             0              13   United-States   
1         Male             0             0              40   United-States   
2         Male             0             0              40   United-States   
3       Female             0             0              40            Cuba   
4       Female             0             0              40   United-States   
...        ...           ...           ...             ...             ...   
32555   Female             0             0              38   United-States   
32556     Male             0             0              40   United-States   
32557   Female             0             0              40   United-States   
32558     Male             0             0              20   United-States   
32559   Female         15024             0              40   United-States   

       income  
0       <=50K  
1       <=50K  
2       <=50K  
3       <=50K  
4       <=50K  
...       ...  
32555   <=50K  
32556    >50K  
32557   <=50K  
32558   <=50K  
32559    >50K  

[32560 rows x 15 columns]

In [9]:
df.isnull().sum()

Age               0
Workclass         0
Fnlwgt            0
Education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [10]:
df.dtypes


Age                int64
Workclass         object
Fnlwgt             int64
Education         object
education_num      int64
marital_status    object
occupation        object
relationship      object
race              object
sex               object
capital_gain       int64
capital_loss       int64
hours_per_week     int64
native_country    object
income            object
dtype: object

In [11]:
df.fillna(method='ffill',inplace=True)

In [12]:
from sklearn.preprocessing import LabelEncoder


In [13]:
lb=LabelEncoder()
df['Workclass']=lb.fit_transform(df['Workclass'])
df['Education']=lb.fit_transform(df['Education'])
df['marital_status']=lb.fit_transform(df['marital_status'])
df['occupation']=lb.fit_transform(df['occupation'])
df['relationship']=lb.fit_transform(df['relationship'])
df['race']=lb.fit_transform(df['race'])
df['sex']=lb.fit_transform(df['sex'])
df['native_country']=lb.fit_transform(df['native_country'])
df['income']=lb.fit_transform(df['income'])
df['Workclass'].value_counts()
df['Education'].value_counts()
df['marital_status'].value_counts()
df['occupation'].value_counts()
df['relationship'].value_counts()
df['race'].value_counts()
df['sex'].value_counts()
df['native_country'].value_counts()
df['income'].value_counts()
df.dtypes


Age               int64
Workclass         int32
Fnlwgt            int64
Education         int32
education_num     int64
marital_status    int32
occupation        int32
relationship      int32
race              int32
sex               int32
capital_gain      int64
capital_loss      int64
hours_per_week    int64
native_country    int32
income            int32
dtype: object

In [14]:
df.head()

Age  Workclass  Fnlwgt  Education  education_num  marital_status  \
0   50          6   83311          9             13               2   
1   38          4  215646         11              9               0   
2   53          4  234721          1              7               2   
3   28          4  338409          9             13               2   
4   37          4  284582         12             14               2   

   occupation  relationship  race  sex  capital_gain  capital_loss  \
0           4             0     4    1             0             0   
1           6             1     4    1             0             0   
2           6             0     2    1             0             0   
3          10             5     2    0             0             0   
4           4             5     4    0             0             0   

   hours_per_week  native_country  income  
0              13              39       0  
1              40              39       0  
2              40              39       0  
3              40               5       0  
4              40              39       0

In [15]:
x=df.drop('income',axis=1)
y=df['income']
print(type(x))
print(type(y))
print(x.shape)
print(y.shape)

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
(32560, 14)
(32560,)


# split-train-test-data

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(22792, 14)
(9768, 14)
(22792,)
(9768,)


# confusion_matrix,classification_report,Accuracy score

In [27]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [28]:
def eval_model(ytest,ypred):
    cm=confusion_matrix(ytest,ypred)
    print(cm)
    print(classification_report(ytest,ypred))
    print("acc score",accuracy_score(ytest,ypred))
def msscore(model):
    print("trainin score",model.score(x_train,y_train))
    print("testing score",model.score(x_test,y_test))

# Logistic Regression

In [37]:
from sklearn.linear_model import LogisticRegression

In [38]:
m1=LogisticRegression(max_iter=1000)
m1.fit(x_train,y_train)
msscore(m1)
ypred_m1=m1.predict(x_test)
eval_model(y_test,ypred_m1)

trainin score 0.7871182871182871
testing score 0.7862407862407862
[[6987  408]
 [1680  693]]
              precision    recall  f1-score   support

           0       0.81      0.94      0.87      7395
           1       0.63      0.29      0.40      2373

    accuracy                           0.79      9768
   macro avg       0.72      0.62      0.63      9768
weighted avg       0.76      0.79      0.76      9768

acc score 0.7862407862407862


In [39]:
cm1 = confusion_matrix(y_test,ypred_m1)
print(cm1)

[[6987  408]
 [1680  693]]


# validation

In [40]:
pre0 = 6987/(6987+1680)
pre1 = 693/(693+408)
rec0 = 6987/(6987+408)
rec1 = 693/(693+1680)
print("Pre0",pre0)
print("Pre1",pre1)
print("Rec0",rec0)
print("Rec1",rec1)

Pre0 0.8061613014884043
Pre1 0.6294277929155313
Rec0 0.9448275862068966
Rec1 0.2920353982300885


# f1 score

In [49]:
f1s0 = 2*pre0*rec0/(pre0 + rec0)
f1s1 = 2*pre1*rec1/(pre1 + rec1)
print("F1_Score0 ",f1s0)
print("F1_Score1 ",f1s1)

F1_Score0  0.871268656716418
F1_Score1  0.6485693323550991


# accuracy

In [42]:
acc=(6987+693)/(6987+1680+693+408)
print("Accuracy",acc)

Accuracy 0.7862407862407862


# Misclassification

In [43]:
msc = (408+1680)/(6987+1680+693+408)
print("Misclassification",msc*100)

Misclassification 21.375921375921376


# Decision Tree Classifier

In [45]:
from sklearn.tree import DecisionTreeClassifier

In [46]:
m2=DecisionTreeClassifier(criterion='gini',min_samples_split=15,max_depth=8)
m2.fit(x_train,y_train)
msscore(m2)
ypred_m2=m2.predict(x_test)
eval_model(y_test,ypred_m2)

trainin score 0.8621007371007371
testing score 0.8528869778869779
[[7005  390]
 [1047 1326]]
              precision    recall  f1-score   support

           0       0.87      0.95      0.91      7395
           1       0.77      0.56      0.65      2373

    accuracy                           0.85      9768
   macro avg       0.82      0.75      0.78      9768
weighted avg       0.85      0.85      0.84      9768

acc score 0.8528869778869779


In [47]:
cm2 = confusion_matrix(y_test,ypred_m2)
print(cm2)

[[7005  390]
 [1047 1326]]


# validation

In [58]:
pre0 = 7005/(7005+1047)
pre1 = 1326/(1326+390)
rec0 = 7005/(7005+390)
rec1 = 1326/(1326+1047)
print("Pre0",pre0)
print("Pre1",pre1)
print("Rec0",rec0)
print("Rec1",rec1)

Pre0 0.8699701937406855
Pre1 0.7727272727272727
Rec0 0.947261663286004
Rec1 0.5587863463969659


# f1 score

In [59]:
f1s0 = 2*pre0*rec0/(pre0 + rec0)
f1s1 = 2*pre1*rec1/(pre1 + rec1)
print("F1_Score0 ",f1s0)
print("F1_Score1 ",f1s1)

F1_Score0  0.9069722276170129
F1_Score1  0.6485693323550991


# accuracy

In [52]:
acc=(7005+1326)/(7005+1326+1047+390)
print("Accuracy",acc)

Accuracy 0.8528869778869779


# missclassification

In [53]:
msc = (1047+390)/(7005+1326+1047+390)
print("Misclassification",msc*100)

Misclassification 14.71130221130221


# Random forest classifier

In [25]:
from sklearn.ensemble import RandomForestClassifier

In [26]:
m3=RandomForestClassifier(n_estimators=45,criterion='entropy',max_depth=8,min_samples_split=15)
m3.fit(x_train,y_train)
msscore(m3)
ypred_m3=m3.predict(x_test)
eval_model(y_test,ypred_m3)

trainin score 0.8578009828009828
testing score 0.8532964782964783
[[7062  333]
 [1100 1273]]
              precision    recall  f1-score   support

           0       0.87      0.95      0.91      7395
           1       0.79      0.54      0.64      2373

    accuracy                           0.85      9768
   macro avg       0.83      0.75      0.77      9768
weighted avg       0.85      0.85      0.84      9768

acc score 0.8532964782964783


In [56]:
cm3 = confusion_matrix(y_test,ypred_m3)
print(cm3)

[[7067  328]
 [1095 1278]]


# validation

In [63]:
pre0 =7067/(7067+1095)
pre1 = 1278/(1278+328)
rec0 = 7067/(7067+328)
rec1 = 1278/(1278+1095)
print("Pre0",pre0)
print("Pre1",pre1)
print("Rec0",rec0)
print("Rec1",rec1)

Pre0 0.865841705464347
Pre1 0.7957658779576587
Rec0 0.9556457065584855
Rec1 0.538558786346397


# f1 score

In [64]:
f1s0 = 2*pre0*rec0/(pre0 + rec0)
f1s1 = 2*pre1*rec1/(pre1 + rec1)
print("F1_Score0 ",f1s0)
print("F1_Score1 ",f1s1)

F1_Score0  0.908529922221508
F1_Score1  0.6423724553908017


# accuracy

In [65]:
acc=(7076+1278)/(7076+1095+1278+328)
print("Accuracy",acc)

Accuracy 0.8544543315945586


# misclassification

In [66]:
msc = (1278+338)/(7076+1095+1278+328)
print("Misclassification",msc*100)

Misclassification 16.528587501278512


# KNN Classifier

In [68]:
from sklearn.neighbors import KNeighborsClassifier


In [69]:
m4=KNeighborsClassifier(n_neighbors=21)
m4.fit(x_train,y_train)
msscore(m4)
ypred_m4=m4.predict(x_test)
eval_model(y_test,ypred_m4)

C:\Users\dell\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


trainin score 0.8039224289224289


C:\Users\dell\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


testing score 0.7981162981162981


C:\Users\dell\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


[[7300   95]
 [1877  496]]
              precision    recall  f1-score   support

           0       0.80      0.99      0.88      7395
           1       0.84      0.21      0.33      2373

    accuracy                           0.80      9768
   macro avg       0.82      0.60      0.61      9768
weighted avg       0.81      0.80      0.75      9768

acc score 0.7981162981162981


In [70]:
cm4 = confusion_matrix(y_test,ypred_m4)
print(cm4)

[[7300   95]
 [1877  496]]


# validation

In [74]:
pre0 =7300/(7300+1877)
pre1 = 496/(496+95)
rec0 = 7300/(7300+95)
rec1 = 496/(496+1877)
print("Pre0",pre0)
print("Pre1",pre1)
print("Rec0",rec0)
print("Rec1",rec1)

Pre0 0.7954669281900403
Pre1 0.8392554991539763
Rec0 0.9871534820824882
Rec1 0.20901812052254531


# f1-score

In [75]:
f1s0 = 2*pre0*rec0/(pre0 + rec0)
f1s1 = 2*pre1*rec1/(pre1 + rec1)
print("F1_Score0 ",f1s0)
print("F1_Score1 ",f1s1)

F1_Score0  0.8810041033067826
F1_Score1  0.33468286099865047


# accuracy-score

In [76]:
acc=(7300+496)/(7300+496+1877+95)
print("Accuracy",acc)

Accuracy 0.7981162981162981


# misclassification

In [77]:
msc = (1877+95)/(7300+496+1877+95)
print("Misclassification",msc*100)

Misclassification 20.18837018837019


# SVM classifier

In [29]:
from sklearn.svm import LinearSVC

In [30]:
m5 = LinearSVC(dual=False)
m5.fit(x_train,y_train)

LinearSVC(dual=False)

In [35]:
msscore(m5)

trainin score 0.803966303966304
testing score 0.8053849303849304


In [ ]:
ypred_m5 = m5.predict(x_test)
eval_model(y_test,ypred_m5)

In [34]:
cm5 = confusion_matrix(y_test,ypred_m5)
print(cm5)

[[7235  160]
 [1741  632]]


# validation

In [37]:
pre0 = 7235/(7235+1741)
pre1 = 632/(632+160)
rec0 = 7235/(7235+160)
rec1 = 632/(632+1742)
print('Pre0',pre0)
print('Pre1',pre1)
print('Rec0',rec0)
print('Rec1',rec1)

Pre0 0.8060383244206774
Pre1 0.797979797979798
Rec0 0.9783637592968222
Rec1 0.2662173546756529


# f1 score

In [39]:
f1s0 = 2*pre0*rec0/(pre0 + rec0)
f1s1 = 2*pre1*rec1/(pre1 + rec1)
print('F1_Score0',f1s0)
print('F1_Score1',f1s1)

F1_Score0 0.8838800317634841
F1_Score1 0.39924194567277316


# Accuracy

In [40]:
acc=(7235+632)/(632+1742+7235+160)
print("Accuracy",acc)

Accuracy 0.8053024874603337


# misclassification

In [41]:
msc = (1742+160)/(632+1742+7235+160)
print("Misclassification",msc)

Misclassification 0.1946975125396663


# comparision

On comparing all classifications, the Random Forest Classifier is the best among all others.

# conclusion

Hence we conclude that RANDOM FOREST CLASSIFIER gives best accuracy of INCOME